### ISSUE TITLE
Ignition not working after installing this package.

### ISSUE THREAD

**Issue by massimodellarovere** [renatomarinho/laravel-page-speed#116]
The middleware CollapseWhitespace creates problems on the javascript inline part of ignition. Eliminating the indicated line everything works correctly. Laravel 6.5.1

<pre>
$replace = [
    "/\n([\S])/" => '$1',
    "/\r/" => '',
    "/\n/" => '', // Remove this no problem
    "/\t/" => '',
    "/ +/" => ' ',
    "/> +</" => '><',
 ];</pre>

thanks, I hope I was helpful

**Comment by joaorobertopb** [comment]
Will probably be solved in this PR #111

**Comment by KangYoosam** [comment]
I am facing same problem.
Thanks @joaorobertopb , I am looking forward to #111 is merged.

**Comment by sphkress** [comment]
I have pulled branch 2.x and tried, still having the same issues...  if using the following hint:

$replace = [
    "/\n([\S])/" => '$1',
    "/\r/" => '',
    "/\n/" => '', // Remove this no problem
    "/\t/" => '',
    "/ +/" => ' ',

it's working though. But for my HTML I need the collapsewhitespace-method including removal of \n

I have tried to add a semicolon in errorPage.php (by Ignition), but this only solved one issue, therefore i guess the error is not within Pagespeed, but rather in Ignition (e.g. new line instead of semicolon?)

**Comment by joaorobertopb** [comment]
@sphkress thanks for reporting.

**Comment by bytebrain** [comment]
I disabled the page speed on the exceptions by changing the `Handler.php` file:

```php
    protected function whoopsHandler()
    {
        // Disable the page speed package.
        config(['laravel-page-speed.enable' => false]);

        try {
            return app(\Whoops\Handler\HandlerInterface::class);
        } catch (\Illuminate\Contracts\Container\BindingResolutionException $e) {
            return parent::whoopsHandler();
        }
    }
```

**Comment by massimodellarovere** [comment]
Code Debug Screen use this code javascript that is removed for comment. It's a bad technique to execute JavaScript and comment it out if the browser doesn't have JavaScript enabled. It's a technique that I would actually avoid. 

More problems than solutions.  One of the problems is precisely the minification regular expressions that, 99% of the time, remove the code, thinking it's a comment.

```
<script>
    <!--
    function e(){return(e=Object.assign|| ..........
    return c.createElement( ............
     return c.createElement( ............
     return c.createElement( ............
     -->
</script>
```

I use this code before minify code con other packages

```
$content = applyMinifyJsDummy($content);
$content = applyMinifyJsValue($content);

function applyMinifyJsDummy($value)
 {
       return preg_replace('/<script>\s*<!--(.*?)-->\s*<\/script>/s','<script>$1</script>',$value);
 }
function applyMinifyJsValue($value)
 {
      return JSMin::minify($value);
 }
```
Not Problem with Ignition

![image](https://github.com/renatomarinho/laravel-page-speed/assets/5731295/8b14a95a-b32b-4e0b-ae54-ed7c88087778)
